training:
  epochs: 100
  batch_size: 4
  learning_rate: 0.0001
  checkpoints_dir: "/kaggle/working/checkpoints"
data:
  s3_bucket: "noaa-goes16"  # Future me isko "noaa-goes19" kar dena
  download_dir: "/kaggle/working/goes_data"
  year: "2024"              # Year parameter
  start_day: 245            # Sept 1, 2024 (Julian Day)
  end_day: 274              # Sept 30, 2024 (Julian Day)
  frame_step: 3
  crop_size: 512            # Resolution upgrade!