training:
  epochs: 100
  batch_size: 4
  learning_rate: 0.0001
  checkpoints_dir: "/kaggle/working/checkpoints"
data:
  s3_bucket: "noaa-goes16"
  download_dir: "/kaggle/working/goes_data"
  target_days: ["266", "267", "268", "269", "270", "271", "272"] # 1 Week of Hurricane Ian!
  frame_step: 3    # 3 frames skip = 30 minutes gap
  crop_size: 256   # 256x256 GPU safe window